name: technical_ind
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.19+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uni_links: ^0.5.1
  flutter_net_promoter_score: ^1.0.0
  analyzer: ^1.7.1
  bot_toast: ^4.0.1
  bubble: ^1.1.9+1
  cloud_firestore: ^3.1.10
  connectivity: ^3.0.3
  country_icons: ^1.1.1
  cupertino_icons: ^1.0.0
  date_calc: ^0.1.0
  date_time_format: ^2.0.1
  external_app_launcher: ^0.0.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.13.1
  firebase_crashlytics: ^1.0.0
  firebase_dynamic_links: ^0.8.0
  firebase_performance: ^0.6.0
  flutter_keyboard_visibility: ^5.0.0
  flutter_riverpod: ^0.13.1
  flutter_screenutil: ^5.1.1
  flutter_staggered_grid_view: ^0.3.2
  flutter_sticky_header: ^0.5.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_typeahead: ^3.1.1
  flutter_webview_plugin: ^0.4.0
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.0
  grouped_list: ^4.0.0
  horizontal_data_table: ^3.4.1
  html: ^0.15.0
  http: ^0.13.0
  infinite_scroll_pagination: ^3.0.1
  lottie: ^1.0.1
  marquee_text: ^2.0.0
  paytm_allinonesdk: ^1.1.0
  persistent_bottom_nav_bar: ^3.1.0
  # otp_autofill: ^1.1.0
  sms_autofill: ^2.0.1
  pin_code_fields: ^7.0.0
  pull_to_refresh: ^2.0.0
  rating_bar: ^0.2.0
  # razorpay_flutter: ^1.2.5
  responsive_framework: ^0.1.0
  share: ^2.0.1
  shared_preferences: ^2.0.4
  sliding_up_panel: ^1.0.2
  sticky_headers: ^0.2.0
  swipe_gesture_recognizer: ^0.0.2
  syncfusion_flutter_charts: ^19.1.69+1
  syncfusion_flutter_gauges: ^19.1.69
  new_version: ^0.2.2
  syncfusion_flutter_maps: ^19.1.69-beta
  tab_indicator_styler: ^1.0.0
  time_formatter: ^1.0.0
  url_launcher: ^6.0.2
  webview_flutter: ^3.0.2
  whatsapp_unilink: ^1.0.0+1
  in_app_review: ^2.0.2
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0
  launch_review: ^3.0.1
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^8.1.1+1
  workmanager: ^0.4.1
  rate_my_app: ^1.1.1
  get: ^4.3.8
  numeral: ^1.2.5
  intl:
  anim_search_bar: ^2.0.2
  collection: ^1.15.0
  path_provider: ^2.0.8
  youtube_player_flutter: ^8.0.0
  flutter_inappwebview: ^5.3.2
  provider: ^6.0.2
  firebase_analytics: ^9.1.2
  flutter_initicon: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/startIcons/Group 21.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
    - assets/instrument/
    - assets/icons/
    - assets/images/
    - assets/startIcons/
    - assets/nav/
    - web/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
