List<String> bseMenu = [
  'SENSEX',
  'BSE 100',
  'BSE 200',
  'BSE 500',
  'BSE MIDCAP',
  'BSE SMALLCAP',
  'BSE BANKEX',
  'BSE Basic Material',
  'S&P BSE Industrials',
  'BSE CDGS',
  'BSE Energy',
  'BSE IT',
  'BSE Telecom',
  'BSE Utilities',
  'BSE Auto',
  'BSE Cons Durables',
  'BSE CAP GOODS',
  'BSE FMCG',
  'BSE Metal',
  'BSE OIL & GAS',
  'BSE REALTY',
  'BSE POWER',
  'BSE Finance ',
  'BSE HEALTHCARE',
  'BSE TECK',
  'BSE PSU',
  'BSE PRIVATE BANK',
];
List<String> bseCodes = [
  //'all-companies-97',
  'sensex',
  'bse_100',
  'bse_200',
  'bse_500',
  'bse_midcap',
  'bse_smallcap',
  'bse_bankex',
  'bse_basic_materials',
  'sp_bse_industrials',
  'bse_cdgs',
  'bse_energy',
  'bse_it',
  'bse_telecom',
  'bse_utilities',
  'bse_auto',
  'bse_cons_durables',
  'bse_cap_goods',
  'bse_fmcg',
  'bse_metal',
  'bse-oil-&-gas-22',
  'bse_realty',
  'bse_power',
  'bse_finance',
  'bse_healthcare',
  'bse_tech',
  'bse-psu-11',
  'bse_private_bank',
  // 'sp_bse_shariah_50',
  // 'sp_bse_greenex',
  // 'sp_bse_carbonex',
  // 'bse_india_manufacturer',
  // 'bse_allcap',
  // 'bse_largecap',
  // 'bse_midcap_select',
  // 'bse_smallcap_select',
  // 'sp_bse_sensex_1xin',
  // 'sp_bse_enhanced_val',
  // 'bse_sensex_50',
  // 'bse_sensex_next_50',
  // 'bse_bharat_22',
  // 'bse_150_midcap',
  // 'bse_250_smallcap',
  // 'bse_250_largemidcap',
  // 'bse_400_midsmallcap',
  // 'sp_bse_100_esg',
  // 'bse_100_largecap_tmc',
  // 'sp_bse_drug',
  // 'bse-sme-ipo-58',
  // 'bse-ipo-33',
];
List<String> nseMenu = [
  //'All Companies',
  //'Low price High Volume',
  'NIFTY 50',
  'NIFTY BANK',
  'NIFTY Midcap 100',
  'NIFTY NEXT 50',
  'NIFTY 100',
  'Nifty 200',
  'NIFTY 500',
  'NIFTY Smallcap 100',
  'NIFTY MIDCAP 50',
  'India VIX',
  'NIFTY AUTO',
  'NIFTY IT',
  'NIFTY PSU BANK',
  'NIFTY FIN SERVICE ',
  'NIFTY PHARMA',
  'NIFTY FMCG',
  'NIFTY METAL',
  'NIFTY REALTY',
  'NIFTY MEDIA',
  'NIFTY ENERGY',
  'NIFTY PVT BANK',
  'NIFTY INFRA',
  'NIFTY COMMODITIES',
  'NIFTY CONSUMPTION',
  'NIFTY PSE',
  'NIFTY SERV SECTOR',
  'Nifty FinSrv25/50',

  // 'NIFTY MNC',
  // 'NIFTY DIV OPPS 50',
  // 'NIFTY GROWSECT 15',
  // 'NIFTY50 VALUE 20',
  // 'NIFTY MIDCAP 150',
  // 'NIFTY MIDSML 400',
  // 'NIFTY SMLCAP 50',
  // 'NIFTY SMLCAP 250',
  // 'NIFTY LargeMidcap250',
  // 'NIFTY SME EMERGE',
  // 'NIFTY AlphaLowVol30',
  // 'Nifty200 Momentum 30',
  // 'Nifty 100 ESG Sector',
];
List<String> nseCodes = [
  //'all-companies-99',
  'nifty_50',
  'nifty_bank',
  'nifty_midcap_100',
  'nifty_next_50',
  'nifty_100',
  "nifty_200",
  'nifty_500',
  "nifty_smallcap_100",
  "nifty_midcap_50",
  "india_vix",
  "nifty_auto",
  'nifty_it',
  "nifty_psu_bank",
  "nifty_fin_service",
  "nifty_pharma",
  "nifty_fmcg",
  "nifty_metal",
  "mifty_realty",
  "nifty_media",
  "nifty_energy",
  "nifty_pvt_bank",
  "nifty_infra",
  "nifty_commodities",
  "nifty_consumption",
  "nifty_pse",
  "nifty_serv_sector",
  "nifty_finsrv25_50",

  // 'nifty50-usd-8',
  // "nifty_mnc",
  // "nifty_div_opps_50",
  // "nifty_growsect_15",
  // "nifty50_value_20",
  // "nifty_midcap_150",
  // "nifty_midsml_400",
  // "nifty_smlcap_50",
  // "nifty_smlcap_250",
  // "nifty_largemidcap_250",
  // "nifty_sme_emerge",
  // "nifty_alphaLowVol_30",
  // "nifty_200_momentum_30",
  // "nifty100_esg_sector"
];

//servicevalue and servicecodes used in AllStocks page
List<String> sectorValueMenu = [
  "Abrasives",
  "Aerospace & Defence",
  "Agriculture",
  "Air Conditioners",
  "Airlines",
  "Aluminium & Aluminium Products",
  "Amusement Parks/Recreation/Club",
  "Aquaculture",
  "Auto Ancillaries",
  "Auto Ancillaries - Air Conditioning Parts",
  "Auto Ancillaries - Auto, Truck & Motorcycle Parts",
  "Auto Ancillaries - Axle shafts",
  "Auto Ancillaries - Bearings",
  "Auto Ancillaries - Brakes",
  "Auto Ancillaries - Bus Body",
  "Auto Ancillaries - Castings/Forgings",
  "Auto Ancillaries - Clutches",
  "Auto Ancillaries - Diesel Engines",
  "Auto Ancillaries - Engine Parts",
  "Auto Ancillaries - Gears",
  "Auto Ancillaries - Head lamps & lights",
  "Auto Ancillaries - Others",
  "Auto Ancillaries - Pistons",
  "Auto Ancillaries - Seating covers & parts",
  "Auto Ancillaries - Sheet Metals",
  "Auto Ancillaries - Shock absorbers",
  "Auto Ancillaries - Spare Parts & Accessories",
  "Auto Ancillaries - Springs",
  "Auto Ancillaries - Tyres & Rubber Products",
  "Auto Ancillaries - Wheels",
  "Auto Ancillary",
  "Automobile - 2 & 3 Wheelers",
  "Automobile - Auto & Truck Manufacturers",
  "Automobile - Dealers & Distributors",
  "Automobile - LCVS/ HVCS",
  "Automobile - Passenger Cars",
  "Automobile - Tractors",
  "Automobile - Trucks/LCVs",
  "Bank - Private",
  "Bank - Public",
  "Batteries",
  "Beverages",
  "Biotechnology & Medical Research",
  "BPO/ITeS",
  "Breweries & Distilleries",
  "Cable & D2H",
  "Cables",
  "Carbon Black",
  "Cement",
  "Ceramics/Marble/Granite/Sanitaryware",
  "Chemicals",
  "Cigarettes/Tobacco",
  "Coal",
  "Commodity Chemicals",
  "Compressors / Pumps",
  "Computer Peripherals",
  "Construction - Infrastructure",
  "Construction - Real Estate",
  "Construction - Residential & Commercial Complexes",
  "Consumer Food",
  "Containers & Packaging",
  "Courier Services",
  "Cycles",
  "Defence",
  "Detergents & Soaps",
  "Diamond  &  Jewellery",
  "Diversified",
  "Diversified Chemicals",
  "Domestic Appliances",
  "Dyes & Pigments",
  "Educational Institutions",
  "Electric Equipment",
  "Electric Equipment - Boilers / Turbines",
  "Electric Equipment - Switchgears",
  "Electric Equipment - Transformers",
  "Electrodes & Electrical Equipments",
  "Electrodes & Welding Equipment",
  "Electronic Goods",
  "Electronics - Components",
  "Engineering",
  "Engineering & Construction",
  "Engineering - Construction",
  "Engineering - Industrial Equipments",
  // "ETF",
  "Fasteners",
  "Ferro Manganese",
  "Fertilizers",
  "Film Production, Distribution & Entertainment",
  "Finance - Housing",
  "Finance - Investment",
  "Finance - NBFC",
  "Finance - Others",
  "Finance - Stock Broking",
  "Finance Term Lending",
  "Fish/Poultry & Meat Products",
  "Food & Drug Retailing",
  "Food Processing",
  "Footwear",
  "Gas Distribution",
  "Glass & Glass Products",
  "Gold",
  "Gold ETF",
  "Ground Freight & Logistics Services",
  "Hospital & Healthcare Services",
  "Hotel, Resort & Restaurants",
  "Household & Personal Products",
  "Infrastructure",
  "Iron & Steel",
  "IT - Education",
  "IT - Networking",
  "IT Services & Consulting",
  "Labs & Life Sciences Services",
  "Laminates/Decoratives",
  "Leather",
  "Leisure Services",
  "Life & Health Insurance",
  "Logistics",
  "LPG",
  "Lubricants",
  "Media",
  "Medical Equipment/Supplies/Accessories",
  "Metals & Mining",
  "Metals - Castings/Forgings",
  "Metals - Non Ferrous",
  "Misc. Commercial Services",
  "Miscellaneous",
  "Multiline Insurance & Brokers",
  "Oil Exploration and Production",
  "Online Services",
  "other agriculture products",
  "Other Construction Materials",
  "Others-Industrial Gases & Fuels",
  "Others-Manufacturing",
  "Packaging - Films",
  "Packaging - Packaging Materials",
  "Packaging - Polyfilms",
  "Packaging - Sacks and Bags",
  "Packaging Materials-Containers & Packaging",
  "Packaging Materials-Plastic Products",
  "Paints",
  "Paper & Forest Products",
  "Paper & Paper Products",
  "Pesticides & Agrochemicals",
  "Pharmaceuticals & Drugs",
  "Photographic Products",
  "Plastic Products",
  "Plastic Products - Others",
  "Plastics - Moulded Articles and Furnitures",
  "Plastics - Pet Bottels, Jars & Containers",
  "Plastics - Self Adhesive Tapes",
  "Plastics - Thermoplastics",
  "Plastics - Tubes/Pipes/Hoses & Fittings",
  "Ports",
  "Power Generation/Distribution",
  "Printing & Publishing",
  "Printing & Stationery",
  "Printing And Publishing",
  "Railways Wagons",
  "Ratings",
  "Real Estate Operations",
  "Real Estate Rental, Development & Operations",
  "Refineries",
  "Refractories",
  "Reinsurance",
  "Renewables",
  "Retailing",
  "Rubber  Products",
  "Ship Building",
  "Shipping",
  "Software",
  "Solvent  Extraction",
  "Speciality Chemicals",
  "Speciality Retailers",
  "Specialty Mining & Metals",
  "Sugar",
  "Tea/Coffee",
  "Telecommunication - Equipment",
  "Telecommunication - Service Provider",
  "Telecommunications Services",
  "Textile - Machinery",
  "Textile - Spinning",
  "Textiles",
  "Textiles & Apparel",
  "Trading",
  "Transmission Towers / Equipments",
  "Transport Infrastructure",
  "Travel Services",
  "TV Broadcasting & Software Production",
  "Vegetable Oils & Products",
  "Watches & Accessories",
  "Wood & Wood Products"
];

List<String> sectorValueCodes = [
  "abrasives",
  "aerospace-defence",
  "agriculture",
  "air-conditioners",
  "airlines",
  "aluminium-aluminium-products",
  "amusement-parksrecreationclub",
  "aquaculture",
  "auto-ancillaries",
  "auto-ancillaries-air-conditioning-parts",
  "auto-ancillaries-auto-truck-motorcycle-parts",
  "auto-ancillaries-axle-shafts",
  "auto-ancillaries-bearings",
  "auto-ancillaries-brakes",
  "auto-ancillaries-bus-body",
  "auto-ancillaries-castingsforgings",
  "auto-ancillaries-clutches",
  "auto-ancillaries-diesel-engines",
  "auto-ancillaries-engine-parts",
  "auto-ancillaries-gears",
  "auto-ancillaries-head-lamps-lights",
  "auto-ancillaries-others",
  "auto-ancillaries-pistons",
  "auto-ancillaries-seating-covers-parts",
  "auto-ancillaries-sheet-metals",
  "auto-ancillaries-shock-absorbers",
  "auto-ancillaries-spare-parts-accessories",
  "auto-ancillaries-springs",
  "auto-ancillaries-tyres-rubber-products",
  "auto-ancillaries-wheels",
  "auto-ancillary",
  "automobile-2-3-wheelers",
  "automobile-auto-truck-manufacturers",
  "automobile-dealers-distributors",
  "automobile-lcvs-hvcs",
  "automobile-passenger-cars",
  "automobile-tractors",
  "automobile-truckslcvs",
  "bank-private",
  "bank-public",
  "batteries",
  "beverages",
  "biotechnology-medical-research",
  "bpoites",
  "breweries-distilleries",
  "cable-d2h",
  "cables",
  "carbon-black",
  "cement",
  "ceramicsmarblegranitesanitaryware",
  "chemicals",
  "cigarettestobacco",
  "coal",
  "commodity-chemicals",
  "compressors-pumps",
  "computer-peripherals",
  "construction-infrastructure",
  "construction-real-estate",
  "construction-residential-commercial-complexes",
  "consumer-food",
  "containers-packaging",
  "courier-services",
  "cycles",
  "defence",
  "detergents-soaps",
  "diamond-jewellery",
  "diversified",
  "diversified-chemicals",
  "domestic-appliances",
  "dyes-pigments",
  "educational-institutions",
  "electric-equipment",
  "electric-equipment-boilers-turbines",
  "electric-equipment-switchgears",
  "electric-equipment-transformers",
  "electrodes-electrical-equipments",
  "electrodes-welding-equipment",
  "electronic-goods",
  "electronics-components",
  "engineering",
  "engineering-construction",
  "engineering-construction",
  "engineering-industrial-equipments",
  // "etf",
  "fasteners",
  "ferro-manganese",
  "fertilizers",
  "film-production-distribution-entertainment",
  "finance-housing",
  "finance-investment",
  "finance-nbfc",
  "finance-others",
  "finance-stock-broking",
  "finance-term-lending",
  "fishpoultry-meat-products",
  "food-drug-retailing",
  "food-processing",
  "footwear",
  "gas-distribution",
  "glass-glass-products",
  "gold",
  "gold-etf",
  "ground-freight-logistics-services",
  "hospital-healthcare-services",
  "hotel-resort-restaurants",
  "household-personal-products",
  "infrastructure",
  "iron-steel",
  "it-education",
  "it-networking",
  "it-services-consulting",
  "labs-life-sciences-services",
  "laminatesdecoratives",
  "leather",
  "leisure-services",
  "life-health-insurance",
  "logistics",
  "lpg",
  "lubricants",
  "media",
  "medical-equipmentsuppliesaccessories",
  "metals-mining",
  "metals-castingsforgings",
  "metals-non-ferrous",
  "misc-commercial-services",
  "miscellaneous",
  "multiline-insurance-brokers",
  "oil-exploration-and-production",
  "online-services",
  "other-agriculture-products",
  "other-construction-materials",
  "others-industrial-gases-fuels",
  "others-manufacturing",
  "packaging-films",
  "packaging-packaging-materials",
  "packaging-polyfilms",
  "packaging-sacks-and-bags",
  "packaging-materials-containers-packaging",
  "packaging-materials-plastic-products",
  "paints",
  "paper-forest-products",
  "paper-paper-products",
  "pesticides-agrochemicals",
  "pharmaceuticals-drugs",
  "photographic-products",
  "plastic-products",
  "plastic-products-others",
  "plastics-moulded-articles-and-furnitures",
  "plastics-pet-bottels-jars-containers",
  "plastics-self-adhesive-tapes",
  "plastics-thermoplastics",
  "plastics-tubespipeshoses-fittings",
  "ports",
  "power-generationdistribution",
  "printing-publishing",
  "printing-stationery",
  "printing-and-publishing",
  "railways-wagons",
  "ratings",
  "real-estate-operations",
  "real-estate-rental-development-operations",
  "refineries",
  "refractories",
  "reinsurance",
  "renewables",
  "retailing",
  "rubber-products",
  "ship-building",
  "shipping",
  "software",
  "solvent-extraction",
  "speciality-chemicals",
  "speciality-retailers",
  "specialty-mining-metals",
  "sugar",
  "teacoffee",
  "telecommunication-equipment",
  "telecommunication-service-provider",
  "telecommunications-services",
  "textile-machinery",
  "textile-spinning",
  "textiles",
  "textiles-apparel",
  "trading",
  "transmission-towers-equipments",
  "transport-infrastructure",
  "travel-services",
  "tv-broadcasting-software-production",
  "vegetable-oils-products",
  "watches-accessories",
  "wood-wood-products"
];
